name: Flake8 Styling

on:
  push:
    branches:
    - master
    - dev
    paths:
    - bungio/**/*.py
  pull_request:
    branches:
    - master
    - dev
    paths:
    - bungio/**/*.py

jobs:
  flake8:
    name: Flake8

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Lint with flake8
        run: |
          pip install flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings
          flake8 --count --exit-zero --ignore=F401,F403,F405,W503,W605 --max-complexity=10 --max-line-length=999 --statistics
