name: Ruff Formating

on:
  push:
    branches:
      - master
      - dev
    paths:
      - src/**/*.py
      - tests/**/*.py
  pull_request:
    branches:
      - master
      - dev
    paths:
      - src/**/*.py
      - tests/**/*.py

jobs:
  ruff:
    name: Ruff Formating

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Ruff Formating
        uses: chartboost/ruff-action@v1
        with:
          args: "format --check"
          changed-files: "true"
